title: From 'yes' to wesele
description: A quick guide to getting married in Poland
theme: just-the-docs

url: https://laitavistula.github.io/FromYesJTD

aux_links: 
  Project Repository: https://github.com/laitavistula/FromYesJTD
logo: "images/From ‘yes’ to wesele (200 x 43 px).svg"
