title: From 'yes' to wesele
description: A quick guide to getting married in Poland
theme: just-the-docs

url: https://laitavistula.github.io/FromYesJTD

aux_links: 
  Project Repository: https://github.com/laitavistula/FromYesJTD/
